name: Run TextLint Rules
'on':
  workflow_call:
    inputs:
      rules:
        type: string
        description: JSON array of textlint rule packages
        required: true
        default: '["textlint-rule-no-todo", "textlint-rule-alex"]'
jobs:
  textLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install textlint
        run: npm install --save-dev textlint jq
      - name: Install textlint rules
        run: >
          rules_json=${{ toJson(github.event.inputs.rules) ||
          '["textlint-rule-no-todo", "textlint-rule-alex"]' }}

          rules_array=$(echo $rules_json | jq -r '.[]')

          for rule in $rules_array

          do
            npm install --save-dev $rule
          done
      - name: Create textlint config file
        run: |
          rules_json=${{ toJson(github.event.inputs.rules) || '["textlint-rule-no-todo", "textlint-rule-alex"]' }}
          echo "{ \"rules\": {" > .textlintrc
          rules_array=$(echo $rules_json | jq -r '.[]' | sed -e 's/^/\"/' -e 's/$/\": true,/' )
          echo $rules_array | sed 's/,$//' >> .textlintrc
          echo "} }" >> .textlintrc
      - name: Run textlint
        run: npx textlint "**/*.md"
